# Generated by Django 2.2.19 on 2023-01-17 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='softwear',
            name='progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Progress'),
        ),
        migrations.AlterField(
            model_name='softwear',
            name='softwear',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('hosted_link', models.URLField()),
                ('extra_description_link', models.URLField()),
                ('github_link', models.URLField()),
                ('imges', models.ManyToManyField(blank=True, null=True, to='portfolio.Image')),
                ('progress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Progress')),
                ('tools', models.ManyToManyField(blank=True, related_name='sw_projects', to='portfolio.Softwear')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(auto_now_add=True)),
                ('phone_no', models.IntegerField()),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('degree', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('cerificates', models.TextField(blank=True, null=True)),
                ('intrests', models.TextField(blank=True, null=True)),
                ('projects', models.ManyToManyField(blank=True, to='portfolio.Project')),
                ('softwears', models.ManyToManyField(to='portfolio.Softwear')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
