# Generated by Django 4.1.5 on 2023-01-17 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20230117_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperiance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(max_length=100)),
                ('company_type', models.CharField(max_length=100)),
                ('date_of_join', models.DateField(null=True)),
                ('date_on_finish', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='imges',
        ),
        migrations.AddField(
            model_name='project',
            name='more_imges',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects_sub_img', to='portfolio.image'),
        ),
        migrations.AddField(
            model_name='project',
            name='small_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_tumb', to='portfolio.image'),
        ),
    ]
