# Generated by Django 4.1.5 on 2023-01-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_testimonial_workexperiance_remove_project_imges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwear',
            name='small_skill',
            field=models.BooleanField(default=True),
        ),
    ]
